services:
  wordpress01:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress01
      WORDPRESS_DB_PASSWORD: secure_pass
      WORDPRESS_DB_NAME: wordpress01
    volumes:
      - wordpress_data01:/var/www/html
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress01.rule=Host(`wordpress01.vps1.m89.pl`)"
        - "traefik.http.routers.wordpress01.entrypoints=websecure"
        - "traefik.http.routers.wordpress01.tls.certresolver=le"
        - "traefik.http.services.wordpress01.loadbalancer.server.port=80"
    networks:
      - traefik-net

  db01:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_secure_pass
      MYSQL_DATABASE: wordpress01
      MYSQL_USER: wordpress01
      MYSQL_PASSWORD: secure_pass
    volumes:
      - db_data01:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - traefik-net

volumes:
  wordpress_data01:
  db_data01:

networks:
  traefik-net:
    external: true
