name: Deploy wp-stack-01
on:
#  push:
#    branches: [ master ]
  workflow_dispatch:
    inputs:
     descr:
        description: "Dodaj opis dla wykonania"
        default: "Testowanie publikacji"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and load
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: localtest/wp-stack01:latest

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: localtest/wp-stack01:latest
          dockerfile: ./Dockerfile
          severity_threshold: HIGH
          ignore_unfixed: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ra4z1k/wp-stack01:latest

  deploy_via_ssh:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Kopiowanie plików na serwer i uruchomienie docker-compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-stack.yml"
          target: "~/app"

      - name: Deployment aplikacji przez SSH (docker-compose)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/app
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker stack deploy -c docker-stack.yml wp-stack01
